repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        entry: ./.golangci-lint.sh
        language: system
        types: [go]
        pass_filenames: false

      - id: go-fmt
        name: go fmt
        entry: gofmt
        args: [-w, -s]
        language: system
        files: \.go$

      - id: go-imports
        name: go imports
        entry: goimports
        args: [-w]
        language: system
        files: \.go$

      - id: go-test
        name: go test
        entry: go test
        args: [-v, ./...]
        language: system
        pass_filenames: false
